version: "3.8"

name: postgres_local

services:
  postgresql:
    image: postgres:17.2-alpine
    container_name: postgres_local
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 127.0.0.1:5432-5438:5432-5438
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
